### PR TITLE
README.md: fix link to contributors

### PR DESCRIPTION
**Pull request by kenyon**

### CODE REVIEW

**Comment by wooorm** [comment]
Oh, confusing how GH works. Perhaps making it absolute would make it more understandable, while doing the same?

```
https://github.com/RichardLitt/standard-readme/graphs/contributors
```

**Comment by RichardLitt** [comment]
Ping!

**Comment by kenyon** [comment]
> Ping!

Up to you whether you want a relative or absolute link, whatever you think is more readable and maintainable.

**Comment by RichardLitt** [comment]
Merged! Thank you.

**Pull request merged**
