### PR TITLE
the long last remained job for Chinesization  of spec.md got finished

### PR DESCRIPTION
**Pull request by notfresh**
sorry, too lazy and too tired for the long last job, the spec.md translation. 
I got finished it.
Please view and check it.

### CODE REVIEW

**Comment by wooorm** [comment]
Nice! One thing though: BCP 47 uses `-` instead of `_`. Could you change `zh_CN` to `zh-CN`?

**Comment by notfresh** [comment]
OK，fix it

**Comment by wooorm** [comment]
Looks good to me, thanks! I’ll leave it up to @RichardLitt to merge if acceptable!

**Comment by RichardLitt** [comment]
Amazing!  Thank you. 

The only thing I don't know is that it has conflicts with master; can you resolve them, first?

**Comment by notfresh** [comment]
> Amazing! Thank you.
> 
> The only thing I don't know is that it has conflicts with master; can you resolve them, first?

OK, I will do it soon, sorry for that~

**Pull request closed without merging**
