### PR TITLE
Make install and usage optional for doc repos

### PR DESCRIPTION
**Pull request by RichardLitt**
See https://github.com/RichardLitt/standard-readme/issues/21

What do you think, @JesseWeinstein?

### CODE REVIEW

**Comment by JesseWeinstein** [comment]
The **Status** sections still say they are required. Wouldn't it be better to put the conditional there, rather than down in in **Suggestions** sections?

**Comment by RichardLitt** [comment]
That was a messaging priority; might be better to state multiple types of requirements. 

How does that update look?

**Comment by JesseWeinstein** [comment]
Update looks good. What did you mean by "a messaging priority"?

**Comment by RichardLitt** [comment]
I meant that, for most use cases, it is required, and I wanted to make sure that most users saw that. But you're right, this is more elegant.

**Pull request merged**
